# Generated by Django 2.0.2 on 2018-02-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('alliance', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default='R', max_length=4)),
                ('start_pos', models.PositiveSmallIntegerField(choices=[('One', 1), ('Two', 2), ('Three', 3)], default='One')),
                ('auto_cross', models.BooleanField(default=False)),
                ('auto_scale', models.PositiveSmallIntegerField()),
                ('auto_switch', models.PositiveSmallIntegerField()),
                ('portal_pickup', models.PositiveSmallIntegerField()),
                ('ground_pickup', models.PositiveSmallIntegerField()),
                ('tele_switch', models.PositiveSmallIntegerField()),
                ('tele_scale', models.PositiveSmallIntegerField()),
                ('tele_exchange', models.PositiveSmallIntegerField()),
                ('climb_attempt', models.BooleanField(default=False)),
                ('climb_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('frcKey', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scorer.Team'),
        ),
    ]
