# Generated by Django 2.0.2 on 2018-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comments',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='match',
            name='parked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='start_pos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
    ]
