# Generated by Django 2.0.2 on 2018-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0003_remove_match_parked'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='parked',
            field=models.BooleanField(default=False),
        ),
    ]
