# Generated by Django 2.0.2 on 2018-03-08 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0004_match_parked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.PositiveSmallIntegerField()),
                ('auto_cross_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('auto_cubes_per_match', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cubes_scored', models.DecimalField(decimal_places=2, max_digits=3)),
                ('scale_per_match', models.DecimalField(decimal_places=2, max_digits=3)),
                ('switch_per_match', models.DecimalField(decimal_places=2, max_digits=3)),
                ('exchg_per_match', models.DecimalField(decimal_places=2, max_digits=3)),
                ('climb_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency', to='scorer.Team')),
            ],
        ),
    ]
