# Generated by Django 2.0.2 on 2018-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0005_teamefficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamefficiency',
            name='auto_cross_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='auto_cubes_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='climb_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='cubes_scored',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='exchg_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='match_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='scale_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='switch_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
