# Generated by Django 2.0.2 on 2018-03-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0006_auto_20180308_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamefficiency',
            name='auto_cross_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='auto_cubes_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='climb_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='cubes_scored',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='exchg_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='scale_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamefficiency',
            name='switch_per_match',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
